todo:
     image:   tsongpon/todo:${BUILD_NAME}
     mem_limit: 1073741824
     ports:
        - "8090:8090"
     environment:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}