spring:
  datasource:
    url: jdbc:mysql://todo-db.cwng6q80blt8.ap-southeast-1.rds.amazonaws.com:3306/todo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
#DO NOT change this property value, this can cause lost all data in database
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090