spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: todo
    password: pingu123
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
#DO NOT change this property value, this can cause lost all data in database
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090